### ISSUE TITLE
Please add GG SMP

### ISSUE THREAD

**Issue by ARegularUser111** [darverdevs/ESL-Suggestions#1]
GG SMP is a relatively popular server, which got 70 players daily if I rember correctly before summer. Removing the server becuase you have some dumb stupid drama with one of the devs is really ignorant. I remember the server had 30+ votes at the time it was removed. If the whole point of it is to let the users decide who was voting, then why are you so biased aganst this one server? I'm personally very active on GG SMP and love the custom items and think it is very stupid that's it's not on the server list. GG SMP exists and is popular on eaglercraft, and pretending it just doesn't exist on the server list, is just stupid. GG SMP is not a bad server. Have you noticed that no one in the server talks about that dumb drama, regardless about their opinion on it? Please add the server back, it deserves a chance like all the other servers.

**Comment by cire3wastaken** [comment]
CRY!!!!!!!!!!!!!!!!!!!

**Comment by ColdDev** [comment]
Unfortunately, GGSMP is not removed from the server list due to some "dumb drama." GGSMP is removed from the server list for two other reasons.
1) The server is associated with Server.so, an individual who has sparked controversy in the past after making DDoS threats towards other popular servers. The main operator, Solenten/LuckierSnail refused to part ways with him, and we did not want our site to be associated with such an individual, therefore we de-listed the server from our site.
2) Both Solenten and Server.so are banned from the site. Because these two people are the main operators of the server, this makes it impossible for us to have somebody to manage the server and therefore the server will not be brought back.

Hope this helps.

**Comment by ColdDev** [comment]
Additionally, while the site's intention is to allow users to vote on their favorite servers, we are under no obligation to allow democracy to control the entire website. We are also responsible for ensuring the community remains safe, and based off of Server.so's past threats as well as recent behavior, we fear that users may not be safe on GGSMP. This is another big factor that led to our decision to de-list GGSMP.
